$(document).ready(function() {
    var headerTitle = $('header > h1').text();
    var headerCont = '<div class="header-area">';
    headerCont += '<div class="ui-inner ui-pager"><!-- //[D] 헤더가 없는 경우, ui-pager class 추가처리 -->';
    headerCont += '  <div class="ui-left">';
    headerCont += '      <h1 class="page-move">';
    headerCont += '        <button type="button" class="bk-icon-only">';
    headerCont += '          <i class="bk-icon bk-icon-gnb-prev">이전</i>';
    headerCont += '        </button>';
    headerCont += '        <span>' + headerTitle + '</span>';
    headerCont += '      </h1>';
    headerCont += '  </div>';
    headerCont += '  <div class="my-util">';
    headerCont += '    <button type="button" class="bk-icon-only icon-search">';
    headerCont += '      <i class="bk-icon bk-icon-searchBlack">검색</i>';
    headerCont += '    </button>';
    headerCont += '    <div class="cp-search search-top" style="display: none">';
    headerCont += '      <div class="search-area">';
    headerCont += '        <div class="bk-select select-search">';
    headerCont += '          <!--// [D]사이즈:xsmall-20px,small-32px,default-40px,large-48px,xlarge-60px -->';
    headerCont += '          <div class="bk-control">';
    headerCont += '            <select class="" id="" title="검색 메뉴 선택">';
    headerCont += '              <!--// [D]디자인상 label이 없는 타입일 경우 select에 title값으로 label텍스트값으로 처리 -->';
    headerCont += '              <option data-display="Select">ALL</option>';
    headerCont += '              <option value="1">Product Name</option>';
    headerCont += '              <option value="2">Company Name</option>';
    headerCont += '              <option value="3">Keyword</option>';
    headerCont += '            </select>';
    headerCont += '          </div>';
    headerCont += '        </div>';
    headerCont += '        <div class="bk-textfield wide textfield-search">';
    headerCont += '          <!--// [D]상태 class="is-focus,is-disabled,is-required,is-readonly" / 아이콘 class="prepend-icon(아이콘-앞),append-icon(아이콘-뒤)" -->';
    headerCont += '          <!--// [D]사이즈:xsmall-20px,small-32px,default-40px,large-48px,xlarge-60px -->';
    headerCont += '          <div class="bk-control">';
    headerCont += '            <div class="control-field">';
    headerCont += '              <input type="text" name="" value="" placeholder="Im looking for..." class="iText" id=""/>';
    headerCont += '              <div class="control-icon append-icon">';
    headerCont += '                <button type="button" class="bk-icon-only icon-search">';
    headerCont += '                  <i class="bk-icon bk-icon-searchPrimary">검색</i>';
    headerCont += '                </button>';
    headerCont += '              </div>';
    headerCont += '            </div>';
    headerCont += '          </div>';
    headerCont += '        </div>';
    headerCont += '      </div>';
    headerCont += '    </div>';
    headerCont += '';
    headerCont += '    <button type="button" class="bk-icon-only icon-gnb-menu">';
    headerCont += '      <i class="bk-icon bk-icon-gnb-menu">메뉴</i>';
    headerCont += '    </button>';
    headerCont += '    <nav id="gnb" class="ui-gnb">';
    headerCont += '      <div class="ui-inner">';
    headerCont += '        <div class="all-menu">';
    headerCont += '          <button type="button" class="bk-btn-icon btn-text bk-btn-allCategories">';
    headerCont += '            <i class="bk-icon bk-icon-allCategories">마이페이지</i>';
    headerCont += '            <span class="txt">Categories</span>';
    headerCont += '          </button>';
    headerCont += '        </div>';
    headerCont += '        <div class="gnb-menu">';
    headerCont += '          <ul class="list-menu">';
    headerCont += '            <li><a href="#none">Products</a></li>';
    headerCont += '            <li><a href="#none">Companies</a></li>';
    headerCont += '            <li><a href="#none">Shows</a></li>';
    headerCont += '            <li><a href="#none">Global Offices</a></li>';
    headerCont += '            <li><a href="#none">Inquiries</a></li>';
    headerCont += '            <li><a href="#none">Global Partnership</a></li>';
    headerCont += '            <li><a href="#none">Help</a></li>';
    headerCont += '          </ul>';
    headerCont += '        </div>';
    headerCont += '      </div>';
    headerCont += '    </nav>';
    headerCont += '  </div>';
    headerCont += '</div>';
    headerCont += '</div>';

    var footerCont = '<div class="ui-inner">';
    footerCont += '    <div class="corp-area">';
    footerCont += '    <div class="site-group">';
    footerCont += '      <h2 class="logo">';
    footerCont += '        <img src="../../../images/mobile/logo-kotra-dark.svg" alt="Kotra Trade-Investment Promtion Agency" />';
    footerCont += '      </h2>';
    footerCont += '      <ul class="list-corp">';
    footerCont += '        <li><a href="#none">About Terms</a></li>';
    footerCont += '        <li><a href="#none">Terms of Use</a></li>';
    footerCont += '        <li><a href="#none">Special Terms</a></li>';
    footerCont += '        <li><a href="#none">Privacy Policy</a></li>';
    footerCont += '      </ul>';
    footerCont += '    </div>';
    footerCont += '    <div class="corp-group">';
    footerCont += '        <address class="address">';
    footerCont += '        13, Heolleung-ro, Seocho-gu, Seoul, Korea<br>(Postal Code: 06792)<br>';
    footerCont += '        F. +82-2-3460-7951 / E. buykorea@kotra.or.kr';
    footerCont += '        </address>';
    footerCont += '        <p class="copyright">';
    footerCont += '        Copyright ⓒ 2023 KOTRA & buyKOREA All rights reserved.';
    footerCont += '        </p>';
    footerCont += '    </div>';
    footerCont += '    </div>';
    footerCont += '    <div class="inquiry_area">';
    footerCont += '    <dl class="inquiry-area">';
    footerCont += '      <dt>Inquiry on buy KOREA</dt>';
    footerCont += '      <dd>';
    footerCont += '        <ul class="list-inquiry">';
    footerCont += '            <li><a href="#none" target="_blank">Business Inquiry</a></li>';
    footerCont += '            <li><a href="#none" target="_blank">Product Inquiry</a></li>';
    footerCont += '            <li><a href="#none" target="_blank">Open Inquiry</a></li>';
    footerCont += '            <li><a href="#none" target="_blank">Non Member Inquiry</a></li>';
    footerCont += '        </ul>';
    footerCont += '      </dd>';
    footerCont += '    </dl>';
    footerCont += '    </div>';
    footerCont += '    <div class="aside_area">';
    footerCont += '    <dl class="sns-area">';
    footerCont += '      <dt class="ir-su">SNS</dt>';
    footerCont += '      <dd>';
    footerCont += '        <ul class="list-sns">';
    footerCont += '          <li>';
    footerCont += '            <a href="#none" class="bk-icon-only" target="_blank">';
    footerCont += '                <i class="bk-icon bk-icon-sns-linkedIn">linkedIn</i>';
    footerCont += '            </a>';
    footerCont += '          </li>';
    footerCont += '          <li>';
    footerCont += '            <a href="#none" class="bk-icon-only" target="_blank">';
    footerCont += '                <i class="bk-icon bk-icon-sns-facebook">facebook</i>';
    footerCont += '            </a>';
    footerCont += '          </li>';
    footerCont += '          <li>';
    footerCont += '            <a href="#none" class="bk-icon-only" target="_blank">';
    footerCont += '                <i class="bk-icon bk-icon-sns-twitter">twitter</i>';
    footerCont += '            </a>';
    footerCont += '          </li>';
    footerCont += '          <li>';
    footerCont += '            <a href="#none" class="bk-icon-only" target="_blank">';
    footerCont += '                <i class="bk-icon bk-icon-sns-instagram">instagram</i>';
    footerCont += '            </a>';
    footerCont += '          </li>';
    footerCont += '        </ul>';
    footerCont += '      </dd>';
    footerCont += '    </dl>';
    footerCont += '    <div class="family-area">';
    footerCont += '        <div class="family-group">';
    footerCont += '        <button type="button" class="bk-btn bk-btn-icon" component="dropdownMenu">';
    footerCont += '            <span class="text">Family Site</span>';
    footerCont += '            <span class="deco-icon append-icon">';
    footerCont += '            <i class="bk-icon bk-icon-plus-gray">+</i>';
    footerCont += '            </span>';
    footerCont += '        </button>';
    footerCont += '        <div class="cp-layer layer-dropdown layer-family">';
    footerCont += '            <!--// [D]dim처리시 class="dim", 검정색 dim처리시 class="dim-dark",  흰색 dim처리시 class="dim-light" -->';
    footerCont += '            <div class="layer-inner">';
    footerCont += '            <ul class="list-family">';
    footerCont += '                <li><a href="https://www.kotra.or.kr/english/index.do" target="_blank">KOTRA</a ></li>';
    footerCont += '                <li><a href="https://www.investkorea.org/ik-en/index.do" target="_blank">Invest Korea</a></li>';
    footerCont += '                <li><a href="http://www.buykorea.or.kr" target="_blank">buyKOREA for Seller</a> </li>';
    footerCont += '                <li><a href="https://contactkorea.kotra.or.kr/en/index.do" target="_blank">Recruiting Center</a ></li>';
    footerCont += '                <li><a href="http://kodits.kotra.or.kr" target="_blank">KODITS</a></li>';
    footerCont += '                <li><a href="https://ombudsman.kotra.or.kr/ob-en/index.do"  target="_blank" >OMBUDSMAN</a></li>';
    footerCont += '            </ul>';
    footerCont += '            </div>';
    footerCont += '        </div>';
    footerCont += '        </div>';
    footerCont += '    </div>';
    footerCont += '    </div>';
    footerCont += '</div>';

    var skipCont = '    <!-- [S]바로가기 -->';
    skipCont += '<div id="skip">';
    skipCont += '  <a href="#contents"><span>본문내용 바로가기</span></a>';
    skipCont += '  <a href="#gnb"><span>주메뉴 바로가기</span></a>';
    skipCont += '  <a href="#lnb"><span>서브메뉴 바로가기</span></a>';
    skipCont += '  <a href="#header"><span>해더 바로가기</span></a>';
    skipCont += '  <a href="#footer"><span>푸터 바로가기</span></a>';
    skipCont += '</div>';
    skipCont += '<!--// [E]바로가기 -->';

    $('header').html(headerCont);
    $('footer').html(footerCont);
    $('body').prepend(skipCont);

});